// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Hello from ReScript and React!"
                    }),
                JsxRuntime.jsx("button", {
                      children: "Count: " + String(match[0]),
                      onClick: (function (param) {
                          setCount(function (prev) {
                                return prev + 1 | 0;
                              });
                        })
                    })
              ]
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
